# Generated by Django 2.0.5 on 2018-06-25 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='be_follow',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
