# Generated by Django 2.0.5 on 2018-06-25 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180625_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='be_follow',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
