# Generated by Django 2.0.5 on 2018-06-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180625_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='be_follow',
        ),
        migrations.AddField(
            model_name='user',
            name='be_follow',
            field=models.ManyToManyField(related_name='_user_be_follow_+', to='login.User'),
        ),
    ]
