# Generated by Django 2.0.5 on 2018-06-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20180625_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='user2',
        ),
        migrations.AddField(
            model_name='follow',
            name='user2',
            field=models.ManyToManyField(related_name='user2', to='login.User'),
        ),
    ]
